; generated by PrusaSlicer 3.0.0-alpha11 on 2026-09-01 at 00:00:00 UTC

; printer_model = COREONE
; filament_type = PLA;PETG;PLA
; nozzle_diameter = 0.4,0.4,0.4
; filament used [mm] = 420.00, 0.00, 920.00
; filament used [g] = 1.25, 0.00, 2.75
; estimated printing time (normal mode) = 1m

G1 X1 Y1

; filament used [mm] = 420.00, 0.00, 920.00
; filament used [g] = 1.25, 0.00, 2.75
; total filament used [g] = 4.00
; estimated printing time (normal mode) = 1m

; prusaslicer_config = begin
; printer_model = COREONE
; prusaslicer_config = end
